// Demo data for showcasing the Patent Intelligence platform

export const demoPatents = [
  {
    patent_number: 'US-10123456-B2',
    title: 'Solid-State Battery with Enhanced Ionic Conductivity',
    abstract: 'A solid-state battery comprising a lithium-ion conducting electrolyte with a novel garnet-type structure that achieves ionic conductivity exceeding 1 mS/cm at room temperature. The battery includes a composite cathode with integrated thermal management features for improved safety and cycle life.',
    filing_date: '2018-03-15',
    grant_date: '2020-06-22',
    expiration_date: '2038-03-15',
    assignee_organization: 'QuantumCell Energy Inc.',
    inventors: ['Dr. Sarah Chen', 'Michael Park', 'Jennifer Liu'],
    cpc_codes: ['H01M10/0562', 'H01M10/0525', 'H01M4/62'],
    status: 'active',
    country: 'US',
    citation_count: 45,
    cited_by_count: 23,
    claim_count: 24,
    relevance_score: 0.95,
  },
  {
    patent_number: 'US-9876543-B1',
    title: 'Neural Network Architecture for Autonomous Vehicle Navigation',
    abstract: 'A deep learning system for real-time object detection and path planning in autonomous vehicles. The architecture combines convolutional neural networks with transformer-based attention mechanisms to process multi-sensor data including LiDAR, radar, and camera feeds with sub-10ms latency.',
    filing_date: '2016-11-08',
    grant_date: '2019-02-14',
    expiration_date: '2036-11-08',
    assignee_organization: 'AutoDrive Technologies',
    inventors: ['Alex Rivera', 'Dr. Priya Sharma'],
    cpc_codes: ['G06N3/08', 'G05D1/0212', 'B60W60/00'],
    status: 'active',
    country: 'US',
    citation_count: 78,
    cited_by_count: 156,
    claim_count: 32,
    relevance_score: 0.92,
  },
  {
    patent_number: 'US-11234567-B2',
    title: 'CRISPR-Based Gene Therapy for Hereditary Retinal Disorders',
    abstract: 'A therapeutic method using modified CRISPR-Cas9 systems with enhanced specificity for correcting mutations causing inherited retinal dystrophies. Includes novel lipid nanoparticle delivery system for efficient transduction of photoreceptor cells with minimized off-target effects.',
    filing_date: '2020-05-20',
    grant_date: '2023-01-10',
    expiration_date: '2040-05-20',
    assignee_organization: 'GeneVision Therapeutics',
    inventors: ['Dr. Emma Watson', 'Dr. James Chen', 'Rachel Kim'],
    cpc_codes: ['C12N15/86', 'A61K48/00', 'C12N9/22'],
    status: 'active',
    country: 'US',
    citation_count: 12,
    cited_by_count: 8,
    claim_count: 18,
    relevance_score: 0.89,
  },
  {
    patent_number: 'US-8765432-B2',
    title: 'Carbon Nanotube Composite for Aerospace Applications',
    abstract: 'A lightweight composite material incorporating aligned carbon nanotubes in a polymer matrix achieving tensile strength exceeding 150 GPa while maintaining flexibility. Suitable for aircraft structural components and satellite deployable structures.',
    filing_date: '2014-07-12',
    grant_date: '2017-04-18',
    expiration_date: '2026-03-25',
    assignee_organization: 'AeroMaterials Corp.',
    inventors: ['Dr. Robert Martinez'],
    cpc_codes: ['C08K7/24', 'B64C1/00', 'C01B32/168'],
    status: 'active',
    country: 'US',
    citation_count: 124,
    cited_by_count: 89,
    claim_count: 15,
    relevance_score: 0.87,
    days_until_expiration: 58,
    maintenance_fee_status: 'due_soon',
    next_fee_date: '2026-01-25',
    next_fee_amount: 3750,
  },
  {
    patent_number: 'US-7654321-B1',
    title: 'Quantum-Resistant Cryptographic Protocol',
    abstract: 'A post-quantum cryptographic system based on lattice problems providing security against both classical and quantum computing attacks. Implements efficient key exchange and digital signature schemes suitable for IoT devices with limited computational resources.',
    filing_date: '2012-09-03',
    grant_date: '2015-08-11',
    expiration_date: '2025-12-15',
    assignee_organization: 'SecureQuantum Labs',
    inventors: ['Dr. Alice Quantum', 'Bob Cipher'],
    cpc_codes: ['H04L9/30', 'H04L9/32', 'G06N10/00'],
    status: 'active',
    country: 'US',
    citation_count: 201,
    cited_by_count: 312,
    claim_count: 28,
    relevance_score: 0.85,
    days_until_expiration: 18,
    maintenance_fee_status: 'current',
  },
  {
    patent_number: 'EP-3456789-A1',
    title: 'Biodegradable Packaging from Algae-Based Polymers',
    abstract: 'A method for producing fully biodegradable packaging materials from cultivated microalgae. The resulting bioplastic achieves comparable mechanical properties to conventional polyethylene while degrading completely in marine environments within 6 months.',
    filing_date: '2019-04-22',
    grant_date: '2022-08-30',
    expiration_date: '2039-04-22',
    assignee_organization: 'GreenPack Solutions GmbH',
    inventors: ['Dr. Hans Mueller', 'Dr. Yuki Tanaka'],
    cpc_codes: ['C08L89/00', 'B65D65/46', 'C12P7/62'],
    status: 'active',
    country: 'EP',
    citation_count: 34,
    cited_by_count: 19,
    claim_count: 22,
    relevance_score: 0.83,
  },
  {
    patent_number: 'US-6543210-B2',
    title: 'Piezoelectric Energy Harvesting from Human Motion',
    abstract: 'Wearable device incorporating flexible piezoelectric materials for converting kinetic energy from human movement into electrical power. Achieves up to 5mW continuous output suitable for powering medical sensors and fitness trackers.',
    filing_date: '2010-02-28',
    grant_date: '2013-07-16',
    expiration_date: '2025-08-01',
    assignee_organization: 'KineticPower Inc.',
    inventors: ['Dr. Maria Santos', 'John Lee'],
    cpc_codes: ['H02N2/18', 'A61B5/11', 'H01L41/113'],
    status: 'lapsed',
    country: 'US',
    citation_count: 156,
    cited_by_count: 234,
    claim_count: 20,
    relevance_score: 0.81,
    days_until_expiration: -45,
    maintenance_fee_status: 'overdue',
  },
  {
    patent_number: 'JP-2021567890-A',
    title: 'High-Efficiency Perovskite Solar Cell with Tandem Architecture',
    abstract: 'A tandem solar cell combining perovskite and silicon layers achieving power conversion efficiency exceeding 33%. Includes novel interface engineering to minimize recombination losses and improve long-term stability.',
    filing_date: '2021-01-15',
    grant_date: '2023-09-20',
    expiration_date: '2041-01-15',
    assignee_organization: 'SolarTech Japan Co.',
    inventors: ['Dr. Kenji Yamamoto', 'Dr. Akiko Sato'],
    cpc_codes: ['H01L31/0687', 'H01L31/06', 'H02S40/44'],
    status: 'active',
    country: 'JP',
    citation_count: 8,
    cited_by_count: 4,
    claim_count: 16,
    relevance_score: 0.79,
  },
]

export const demoExpiringPatents = [
  {
    patent_number: 'US-7654321-B1',
    title: 'Quantum-Resistant Cryptographic Protocol',
    abstract: 'A post-quantum cryptographic system based on lattice problems providing security against both classical and quantum computing attacks.',
    expiration_date: '2025-12-15',
    filing_date: '2012-09-03',
    grant_date: '2015-08-11',
    assignee_organization: 'SecureQuantum Labs',
    cpc_codes: ['H04L9/30', 'H04L9/32', 'G06N10/00'],
    country: 'US',
    status: 'active',
    days_until_expiration: 18,
    maintenance_fee_status: 'current',
    next_fee_date: null,
    next_fee_amount: null,
    citation_count: 201,
    patent_type: 'utility',
  },
  {
    patent_number: 'US-8765432-B2',
    title: 'Carbon Nanotube Composite for Aerospace Applications',
    abstract: 'A lightweight composite material incorporating aligned carbon nanotubes in a polymer matrix achieving tensile strength exceeding 150 GPa.',
    expiration_date: '2026-03-25',
    filing_date: '2014-07-12',
    grant_date: '2017-04-18',
    assignee_organization: 'AeroMaterials Corp.',
    cpc_codes: ['C08K7/24', 'B64C1/00', 'C01B32/168'],
    country: 'US',
    status: 'active',
    days_until_expiration: 58,
    maintenance_fee_status: 'due_soon',
    next_fee_date: '2026-01-25',
    next_fee_amount: 3750,
    citation_count: 124,
    patent_type: 'utility',
  },
  {
    patent_number: 'US-8234567-B1',
    title: 'Flexible Display with Organic Light-Emitting Diodes',
    abstract: 'A flexible OLED display panel with novel encapsulation technology enabling repeated bending without degradation.',
    expiration_date: '2026-05-10',
    filing_date: '2014-02-28',
    grant_date: '2016-11-15',
    assignee_organization: 'FlexScreen Technologies',
    cpc_codes: ['H10K59/00', 'H10K77/10', 'G09F9/30'],
    country: 'US',
    status: 'active',
    days_until_expiration: 98,
    maintenance_fee_status: 'current',
    next_fee_date: '2026-08-15',
    next_fee_amount: 4100,
    citation_count: 89,
    patent_type: 'utility',
  },
  {
    patent_number: 'US-8567890-B2',
    title: 'Microfluidic Device for Point-of-Care Diagnostics',
    abstract: 'A lab-on-chip platform for rapid molecular diagnostics at point of care with multiplexed detection capability.',
    expiration_date: '2026-07-22',
    filing_date: '2014-05-10',
    grant_date: '2017-01-31',
    assignee_organization: 'DiagnoChip Medical',
    cpc_codes: ['B01L3/5027', 'G01N27/447', 'C12Q1/6834'],
    country: 'US',
    status: 'active',
    days_until_expiration: 172,
    maintenance_fee_status: 'current',
    next_fee_date: '2027-01-31',
    next_fee_amount: 4650,
    citation_count: 67,
    patent_type: 'utility',
  },
]

export const demoExpirationStats = {
  expiring_30_days: 3,
  expiring_90_days: 12,
  expiring_180_days: 28,
  expiring_365_days: 67,
  recently_lapsed: 8,
  pending_maintenance_fees: 15,
  top_sectors: [
    { cpc_code: 'H01L', count: 245 },
    { cpc_code: 'G06N', count: 189 },
    { cpc_code: 'H04L', count: 156 },
    { cpc_code: 'A61K', count: 134 },
    { cpc_code: 'C12N', count: 98 },
  ],
  monthly_timeline: [
    { month: '2026-02', count: 12 },
    { month: '2026-03', count: 18 },
    { month: '2026-04', count: 24 },
    { month: '2026-05', count: 31 },
    { month: '2026-06', count: 28 },
    { month: '2026-07', count: 35 },
    { month: '2026-08', count: 22 },
    { month: '2026-09', count: 19 },
    { month: '2026-10', count: 27 },
    { month: '2026-11', count: 33 },
    { month: '2026-12', count: 41 },
    { month: '2027-01', count: 38 },
  ],
}

export const demoMaintenanceFees = [
  {
    patent_number: 'US-8765432-B2',
    title: 'Carbon Nanotube Composite for Aerospace Applications',
    assignee_organization: 'AeroMaterials Corp.',
    fee_year: 8,
    due_date: '2026-01-25',
    grace_period_end: '2026-07-25',
    amount_usd: 3750,
    days_until_due: 24,
    status: 'upcoming',
  },
  {
    patent_number: 'US-8234567-B1',
    title: 'Flexible Display with Organic Light-Emitting Diodes',
    assignee_organization: 'FlexScreen Technologies',
    fee_year: 8,
    due_date: '2026-02-15',
    grace_period_end: '2026-08-15',
    amount_usd: 4100,
    days_until_due: 45,
    status: 'upcoming',
  },
  {
    patent_number: 'US-9123456-B2',
    title: 'Machine Learning Model for Drug Discovery',
    assignee_organization: 'PharmAI Research',
    fee_year: 4,
    due_date: '2026-03-01',
    grace_period_end: '2026-09-01',
    amount_usd: 2000,
    days_until_due: 59,
    status: 'upcoming',
  },
]

export const demoSimilarPatents = [
  {
    patent_number: 'US-10234567-B2',
    title: 'All-Solid-State Lithium Battery with Sulfide Electrolyte',
    abstract: 'Solid-state battery using argyrodite-type sulfide electrolyte achieving high ionic conductivity and improved interface stability with lithium metal anode.',
    filing_date: '2019-06-15',
    grant_date: '2021-12-07',
    assignee_organization: 'NextGen Battery Corp.',
    cpc_codes: ['H01M10/0562', 'H01M10/0525'],
    country: 'US',
    status: 'active',
    citation_count: 23,
    cited_by_count: 15,
    similarity_score: 0.94,
    source: 'semantic',
  },
  {
    patent_number: 'US-9345678-B1',
    title: 'Thin-Film Solid Electrolyte for Lithium-Ion Batteries',
    abstract: 'Method for depositing thin-film solid electrolyte layers using atomic layer deposition for miniaturized battery applications.',
    filing_date: '2017-03-22',
    grant_date: '2019-08-13',
    assignee_organization: 'MicroPower Systems',
    cpc_codes: ['H01M10/0562', 'C23C16/40'],
    country: 'US',
    status: 'active',
    citation_count: 56,
    cited_by_count: 41,
    similarity_score: 0.87,
    source: 'semantic',
  },
  {
    patent_number: 'EP-3567890-B1',
    title: 'Polymer-Ceramic Composite Electrolyte',
    abstract: 'Hybrid electrolyte combining polymer flexibility with ceramic ionic conductivity for improved safety in electric vehicle batteries.',
    filing_date: '2018-11-08',
    grant_date: '2022-03-15',
    assignee_organization: 'European Battery Alliance',
    cpc_codes: ['H01M10/0565', 'H01M10/0525'],
    country: 'EP',
    status: 'active',
    citation_count: 31,
    cited_by_count: 22,
    similarity_score: 0.82,
    source: 'citation',
  },
]

export const demoTrendsData = {
  period: { start_year: 2016, end_year: 2026 },
  yearly_totals: [
    { year: 2016, count: 145000 },
    { year: 2017, count: 152000 },
    { year: 2018, count: 168000 },
    { year: 2019, count: 175000 },
    { year: 2020, count: 163000 },
    { year: 2021, count: 189000 },
    { year: 2022, count: 215000 },
    { year: 2023, count: 234000 },
    { year: 2024, count: 256000 },
    { year: 2025, count: 278000 },
  ],
  top_cpc_trends: [
    { cpc_code: 'G06N', total_patents: 89234 },
    { cpc_code: 'H01L', total_patents: 76543 },
    { cpc_code: 'H04L', total_patents: 65432 },
    { cpc_code: 'A61K', total_patents: 54321 },
    { cpc_code: 'C12N', total_patents: 43210 },
    { cpc_code: 'H02J', total_patents: 38765 },
    { cpc_code: 'G01N', total_patents: 34567 },
    { cpc_code: 'B60L', total_patents: 29876 },
  ],
  growth_leaders: [
    { cpc_code: 'G06N3/08', recent_count: 12500, earlier_count: 3200, growth_rate: 2.9 },
    { cpc_code: 'H01M10/0525', recent_count: 8900, earlier_count: 2800, growth_rate: 2.18 },
    { cpc_code: 'G16H50/20', recent_count: 5600, earlier_count: 1900, growth_rate: 1.95 },
    { cpc_code: 'Y02E10/50', recent_count: 7800, earlier_count: 3100, growth_rate: 1.52 },
    { cpc_code: 'A61P35/00', recent_count: 4200, earlier_count: 1800, growth_rate: 1.33 },
    { cpc_code: 'H04W4/70', recent_count: 6100, earlier_count: 2900, growth_rate: 1.1 },
    { cpc_code: 'G06Q20/40', recent_count: 3800, earlier_count: 1900, growth_rate: 1.0 },
    { cpc_code: 'C07K16/28', recent_count: 2900, earlier_count: 1500, growth_rate: 0.93 },
  ],
  top_assignees: [
    { assignee: 'Samsung Electronics', patent_count: 15234 },
    { assignee: 'IBM Corporation', patent_count: 12456 },
    { assignee: 'Qualcomm Inc.', patent_count: 11234 },
    { assignee: 'Apple Inc.', patent_count: 9876 },
    { assignee: 'Google LLC', patent_count: 8765 },
    { assignee: 'Microsoft Corporation', patent_count: 8234 },
    { assignee: 'Huawei Technologies', patent_count: 7654 },
    { assignee: 'Intel Corporation', patent_count: 6543 },
  ],
}

export const demoCitationNetwork = {
  center: 'US-10123456-B2',
  nodes: [
    {
      patent_number: 'US-10123456-B2',
      title: 'Solid-State Battery with Enhanced Ionic Conductivity',
      assignee_organization: 'QuantumCell Energy Inc.',
      filing_date: '2018-03-15',
      country: 'US',
      status: 'active',
      cpc_codes: ['H01M10/0562', 'H01M10/0525'],
      citation_count: 45,
      cited_by_count: 23,
      depth: 0,
    },
    {
      patent_number: 'US-9876543-B2',
      title: 'Garnet-Type Solid Electrolyte Composition',
      assignee_organization: 'MIT Energy Research',
      filing_date: '2016-08-22',
      country: 'US',
      status: 'active',
      cpc_codes: ['H01M10/0562'],
      citation_count: 89,
      cited_by_count: 67,
      depth: 1,
    },
    {
      patent_number: 'US-9234567-B1',
      title: 'Interface Modification for Solid Electrolytes',
      assignee_organization: 'Stanford Research',
      filing_date: '2015-04-10',
      country: 'US',
      status: 'active',
      cpc_codes: ['H01M10/0562', 'H01M4/62'],
      citation_count: 156,
      cited_by_count: 112,
      depth: 1,
    },
    {
      patent_number: 'US-10345678-B2',
      title: 'High-Capacity Cathode for Solid-State Batteries',
      assignee_organization: 'QuantumCell Energy Inc.',
      filing_date: '2019-11-30',
      country: 'US',
      status: 'active',
      cpc_codes: ['H01M4/525', 'H01M10/0562'],
      citation_count: 12,
      cited_by_count: 8,
      depth: 1,
    },
    {
      patent_number: 'JP-2017123456-A',
      title: 'Lithium-Ion Conducting Glass-Ceramic',
      assignee_organization: 'Toyota Motor Corp.',
      filing_date: '2014-12-01',
      country: 'JP',
      status: 'active',
      cpc_codes: ['H01M10/0562'],
      citation_count: 234,
      cited_by_count: 189,
      depth: 2,
    },
  ],
  edges: [
    { source: 'US-10123456-B2', target: 'US-9876543-B2', type: 'cites' },
    { source: 'US-10123456-B2', target: 'US-9234567-B1', type: 'cites' },
    { source: 'US-10345678-B2', target: 'US-10123456-B2', type: 'cites' },
    { source: 'US-9876543-B2', target: 'JP-2017123456-A', type: 'cites' },
    { source: 'US-9234567-B1', target: 'JP-2017123456-A', type: 'cites' },
  ],
  total_nodes: 5,
  total_edges: 5,
  depth: 2,
}

export const demoCitationStats = {
  patent_number: 'US-10123456-B2',
  forward_citations: 23,
  backward_citations: 45,
  avg_field_citations: 18.5,
  citation_index: 1.24,
}

export const demoGeneratedIdeas = {
  ideas: [
    {
      title: 'Hybrid Solid-State Battery with Self-Healing Electrolyte',
      description: 'A solid-state battery incorporating microencapsulated liquid electrolyte within a solid matrix that activates upon crack formation to restore ionic pathways, combining the safety of solid electrolytes with the self-repair capability inspired by biological systems.',
      rationale: 'Analysis of expiring patents in H01M10/0562 reveals opportunity to address dendrite formation and interface degradation issues. Cross-referencing with self-healing polymer patents (C08L) suggests novel approach to maintaining electrolyte integrity over extended cycles.',
      target_cpc: 'H01M10/0562',
      inspired_by: ['US-7654321-B1', 'US-8123456-B2'],
      novelty_score: 0.89,
    },
    {
      title: 'AI-Optimized Battery Management Using Quantum Sensing',
      description: 'Integration of quantum magnetometry sensors with machine learning algorithms to precisely monitor internal battery state including lithium plating, SEI growth, and thermal gradients at unprecedented resolution, enabling predictive maintenance and optimal charging strategies.',
      rationale: 'Convergence of declining quantum sensing patents with growing battery management demand. Citation analysis shows limited crossover between G01R33 (magnetic measurement) and H02J7 (battery charging) despite clear synergy potential.',
      target_cpc: 'H02J7/0047',
      inspired_by: ['US-9345678-B1', 'EP-3234567-A1'],
      novelty_score: 0.85,
    },
    {
      title: 'Biodegradable Battery for Single-Use Medical Devices',
      description: 'A fully biodegradable battery using water-activated magnesium-air chemistry with enzyme-degradable polymer casing, specifically designed for implantable sensors and drug delivery devices that dissolve after completing their therapeutic function.',
      rationale: 'White space identified at intersection of biodegradable electronics (H01M6/50) and implantable medical devices (A61B5). Growing number of expiring biocompatible material patents creates opportunity window.',
      target_cpc: 'H01M6/50',
      inspired_by: ['US-8234567-B2', 'EP-2987654-B1'],
      novelty_score: 0.92,
    },
    {
      title: 'Solid-State Battery with Integrated Photovoltaic Charging Layer',
      description: 'A monolithic device combining perovskite solar cell with solid-state battery in a single thin-film stack, enabling self-charging capability for IoT sensors and wearable devices without external connections.',
      rationale: 'Trend analysis shows rapid growth in both solid-state batteries and perovskite solar cells with limited integration attempts. Multiple foundational patents in both domains approaching expiration create freedom to operate.',
      target_cpc: 'H02S40/38',
      inspired_by: ['JP-2021567890-A', 'US-10123456-B2'],
      novelty_score: 0.78,
    },
    {
      title: 'Room-Temperature Sodium-Ion Solid Electrolyte',
      description: 'A NASICON-type solid electrolyte modified with halogen doping to achieve room-temperature ionic conductivity comparable to lithium systems, enabling cost-effective grid-scale energy storage using abundant sodium resources.',
      rationale: 'Supply chain concerns driving interest in non-lithium batteries. Gap analysis reveals declining activity in sodium solid electrolytes despite strong fundamentals from 2010-2015 era patents now expiring.',
      target_cpc: 'H01M10/054',
      inspired_by: ['US-8567890-B1', 'CN-108123456-A'],
      novelty_score: 0.81,
    },
  ],
  focus: 'expiring',
  cpc_prefix: 'H01M',
  seed_patents_used: 12,
  trends_used: 5,
}

export const demoSeedData = {
  expiring_patents: [
    {
      patent_number: 'US-7654321-B1',
      title: 'Quantum-Resistant Cryptographic Protocol',
      abstract: 'Post-quantum cryptographic system based on lattice problems.',
      cpc_codes: ['H04L9/30', 'H04L9/32'],
      expiration_date: '2025-12-15',
      cited_by_count: 312,
      assignee: 'SecureQuantum Labs',
    },
    {
      patent_number: 'US-8123456-B2',
      title: 'Self-Healing Polymer Composite',
      abstract: 'Material with embedded microcapsules for autonomous damage repair.',
      cpc_codes: ['C08L63/00', 'C08K9/10'],
      expiration_date: '2026-02-28',
      cited_by_count: 187,
      assignee: 'SmartMaterials Inc.',
    },
  ],
  growth_areas: [
    { cpc_code: 'G06N3/08', patent_count: 12500 },
    { cpc_code: 'H01M10/0525', patent_count: 8900 },
    { cpc_code: 'G16H50/20', patent_count: 5600 },
    { cpc_code: 'Y02E10/50', patent_count: 7800 },
    { cpc_code: 'A61P35/00', patent_count: 4200 },
  ],
}

export const demoWhiteSpaceSections = {
  sections: [
    { section: 'A', name: 'Human Necessities', total_patents: 2456789, recent_patents: 234567, market_share: 18.2, avg_citations: 12.3, high_impact_count: 15678, momentum: 1.2, trend: 'growing' },
    { section: 'B', name: 'Operations; Transport', total_patents: 1987654, recent_patents: 187654, market_share: 14.7, avg_citations: 10.8, high_impact_count: 12345, momentum: 0.9, trend: 'stable' },
    { section: 'C', name: 'Chemistry; Metallurgy', total_patents: 1876543, recent_patents: 165432, market_share: 13.9, avg_citations: 14.2, high_impact_count: 11234, momentum: 1.1, trend: 'growing' },
    { section: 'G', name: 'Physics', total_patents: 2345678, recent_patents: 287654, market_share: 17.4, avg_citations: 11.5, high_impact_count: 18765, momentum: 1.5, trend: 'growing' },
    { section: 'H', name: 'Electricity', total_patents: 2654321, recent_patents: 312345, market_share: 19.7, avg_citations: 13.1, high_impact_count: 21234, momentum: 1.8, trend: 'growing' },
  ],
}

export const demoWhiteSpaceGaps = {
  white_spaces: [
    {
      cpc_code: 'G06N5/04',
      section: 'G',
      section_name: 'Knowledge representation',
      historical_patents: 12456,
      recent_patents: 2345,
      decline_ratio: 0.81,
      high_impact_count: 156,
      max_citations: 892,
      gap_score: 0.87,
      opportunity_type: 'abandoned_goldmine',
    },
    {
      cpc_code: 'H01L27/115',
      section: 'H',
      section_name: 'Ferroelectric memory',
      historical_patents: 8765,
      recent_patents: 1234,
      decline_ratio: 0.86,
      high_impact_count: 98,
      max_citations: 567,
      gap_score: 0.82,
      opportunity_type: 'consolidation',
    },
    {
      cpc_code: 'C12N15/63',
      section: 'C',
      section_name: 'Recombinant vectors',
      historical_patents: 15678,
      recent_patents: 4567,
      decline_ratio: 0.71,
      high_impact_count: 234,
      max_citations: 1234,
      gap_score: 0.78,
      opportunity_type: 'dormant',
    },
  ],
  total_found: 156,
}

export const demoCrossDomainOpportunities = {
  opportunities: [
    {
      cpc_code: 'A61K48/00',
      section: 'A',
      section_name: 'Gene therapy',
      patent_count: 8765,
      avg_citations: 23.4,
      existing_combinations: 12,
      opportunity_score: 0.89,
      status: 'untapped',
    },
    {
      cpc_code: 'G16H50/20',
      section: 'G',
      section_name: 'Medical data analytics',
      patent_count: 5432,
      avg_citations: 18.7,
      existing_combinations: 34,
      opportunity_score: 0.76,
      status: 'emerging',
    },
    {
      cpc_code: 'C12Q1/6869',
      section: 'C',
      section_name: 'Sequencing methods',
      patent_count: 6789,
      avg_citations: 31.2,
      existing_combinations: 23,
      opportunity_score: 0.81,
      status: 'untapped',
    },
  ],
}

export const demoWatchlistItems = [
  {
    id: 1,
    item_type: 'patent',
    item_value: 'US-10123456-B2',
    name: 'QuantumCell Battery Patent',
    notes: 'Key competitor patent in solid-state space',
    notify_expiration: true,
    notify_maintenance: true,
    is_active: true,
    unread_alerts: 2,
    created_at: '2025-06-15T10:30:00Z',
  },
  {
    id: 2,
    item_type: 'cpc_code',
    item_value: 'H01M10/0562',
    name: 'Solid Electrolytes',
    notes: 'Core technology area for monitoring',
    notify_expiration: true,
    notify_maintenance: false,
    is_active: true,
    unread_alerts: 5,
    created_at: '2025-07-20T14:45:00Z',
  },
  {
    id: 3,
    item_type: 'assignee',
    item_value: 'QuantumCell Energy Inc.',
    name: 'Primary Competitor',
    notes: 'Track all filings',
    notify_expiration: false,
    notify_maintenance: false,
    is_active: true,
    unread_alerts: 1,
    created_at: '2025-08-10T09:15:00Z',
  },
]

export const demoAlerts = [
  {
    id: 1,
    alert_type: 'expiration',
    priority: 'critical',
    title: 'Patent Expiring in 18 Days',
    message: 'US-7654321-B1 (Quantum-Resistant Cryptographic Protocol) will expire on Dec 15, 2025. High citation count (312) suggests significant technology value.',
    related_patent_number: 'US-7654321-B1',
    trigger_date: '2025-11-27',
    is_read: false,
  },
  {
    id: 2,
    alert_type: 'maintenance',
    priority: 'high',
    title: 'Maintenance Fee Due in 24 Days',
    message: 'Year 8 maintenance fee of $3,750 due for US-8765432-B2 (Carbon Nanotube Composite). Grace period ends Jul 25, 2026.',
    related_patent_number: 'US-8765432-B2',
    trigger_date: '2026-01-01',
    is_read: false,
  },
  {
    id: 3,
    alert_type: 'new_filing',
    priority: 'medium',
    title: 'New Filing in Watched CPC',
    message: 'New patent application published in H01M10/0562 by Toyota Motor Corp. May impact competitive landscape.',
    related_patent_number: 'US-2025/0123456',
    trigger_date: '2025-11-25',
    is_read: false,
  },
]

export const demoAlertSummary = {
  total_unread: 8,
  critical_count: 1,
  high_count: 3,
}

export const demoDashboardStats = {
  patents: {
    total: 203456789,
    expiring_90_days: 12453,
  },
  trends: {
    top_cpc: [
      { cpc_code: 'G06N', count: 89234 },
      { cpc_code: 'H01L', count: 76543 },
      { cpc_code: 'H04L', count: 65432 },
    ],
  },
  watchlist: {
    count: 3,
    unread_alerts: 8,
  },
}

export const demoSystemStatus = {
  api_server: 'operational',
  database: 'healthy',
  uspto_ingestion: 'operational',
  epo_integration: 'operational',
  embedding_service: 'healthy',
}
